#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb 14 00:10:54 2021

@author: whoami
"""
prime=[2]
index=10

for i in range(2,index):
    for j in range(2,i):
        if i%j==0:
            j+=1
            continue
        else:
            prime.append(i)

print(prime)
# print(prime[len(prime)-1])
